// Copyright (c) 2025 Jordan Sterling Farr
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Nucleus.Abstractions;

/// <summary>
/// Represents a response sent from the Nucleus API Service back to a Client Adapter.
/// See: Docs/Architecture/ClientAdapters/ARCHITECTURE_ADAPTER_INTERFACES.md
/// See: Docs/Architecture/Processing/ARCHITECTURE_PROCESSING_ORCHESTRATION.md
/// </summary>
/// <param name="Success">Indicates whether the processing was successful.</param>
/// <param name="ResponseMessage">The primary message to be displayed to the user.</param>
/// <param name="ErrorMessage">Details of any error that occurred (null on success).</param>
/// <param name="SentMessageId">Optional: The ID of the message sent by the Notifier, if applicable.</param>
/// <param name="GeneratedArtifactReference">Optional: Reference to any artifact generated by Nucleus (e.g., a data visualization HTML file).</param>
public record AdapterResponse(
    bool Success,
    string ResponseMessage,
    string? ErrorMessage = null,
    string? SentMessageId = null,
    ArtifactReference? GeneratedArtifactReference = null); // Assuming generated artifacts might need referencing back
