// Copyright (c) 2025 Jordan Sterling Farr
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text.Json;

namespace Nucleus.Abstractions.Models.ApiContracts;

/// <summary>
/// Represents a response sent from the Nucleus API Service back to a Client Adapter.
/// See: Docs/Architecture/ClientAdapters/ARCHITECTURE_ADAPTER_INTERFACES.md
/// See: Docs/Architecture/Processing/ARCHITECTURE_PROCESSING_ORCHESTRATION.md
/// </summary>
/// <seealso cref="../../../../Docs/Architecture/12_ARCHITECTURE_ABSTRACTIONS.md"/>
/// <seealso cref="../../../../Docs/Architecture/10_ARCHITECTURE_API.md"/>
/// <seealso cref="../../../../Docs/Architecture/05_ARCHITECTURE_CLIENTS.md"/>
/// <seealso cref="../../../../Docs/Architecture/ClientAdapters/ARCHITECTURE_ADAPTER_INTERFACES.md"/>
/// <seealso cref="../../../../Docs/Architecture/Api/ARCHITECTURE_API_CLIENT_INTERACTION.md"/>
/// <param name="Success">Indicates whether the operation requested by the client was successfully processed by the API.</param>
/// <param name="ResponseMessage">A user-friendly message describing the outcome or providing results (e.g., summary, status update).</param>
/// <param name="ErrorMessage">Details about any error that occurred, if Success is false.</param>
/// <param name="SentMessageId">Optional: The ID of the message sent by the Notifier, if applicable.</param>
/// <param name="GeneratedArtifactReference">Optional: Reference to any artifact generated by Nucleus (e.g., a data visualization HTML file).</param>
/// <param name="AnalysisData">Optional: Structured data resulting from the persona's analysis or execution, intended for persistence.</param>
public record AdapterResponse(
    bool Success,
    string ResponseMessage,
    string? ErrorMessage = null,
    string? SentMessageId = null,
    ArtifactReference? GeneratedArtifactReference = null,
    JsonElement? AnalysisData = null); // Add AnalysisData property (use object for now, refine later if needed)
