// Copyright (c) 2025 Jordan Sterling Farr
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

namespace Nucleus.Abstractions;

/// <summary>
/// Standardized response structure sent from the Nucleus API Service back to a client adapter.
/// </summary>
public record AdapterResponse(
    /// <summary>
    /// The primary textual response generated by the Nucleus system.
    /// </summary>
    string ResponseText,

    /// <summary>
    /// Optional. List of identifiers for sources used to generate the response.
    /// These could be artifact identifiers or other contextual references.
    /// </summary>
    List<string>? SourceReferences = null,

    /// <summary>
    /// Optional. Indicates if an error occurred during processing.
    /// </summary>
    bool IsError = false,

    /// <summary>
    /// Optional. Error message if IsError is true.
    /// </summary>
    string? ErrorMessage = null
);
