name: PR & Develop Branch Validation

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

env:
  DOTNET_VERSION: '9.0.x'
  SOLUTION_FILE_PATH: ./Nucleus.sln

jobs:
  build_lint_unit_test:
    name: Build, Lint & Unit Test
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ job.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build Solution
        run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --configuration Release --no-restore

      - name: Lint Code (Format Check)
        run: dotnet format ${{ env.SOLUTION_FILE_PATH }} --verify-no-changes --verbosity diagnostic

      - name: Run Unit Tests
        run: >
          dotnet test ${{ env.SOLUTION_FILE_PATH }} 
          --configuration Release 
          --no-build 
          --filter "Category!=Integration"
          --logger "trx;LogFileName=unit_test_results.trx"
      
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: "**/unit_test_results.trx"

  integration_test:
    name: Integration Tests (.NET Aspire)
    runs-on: ubuntu-latest
    needs: build_lint_unit_test
    if: >
      needs.build_lint_unit_test.outputs.build_status == 'success' &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && github.ref == 'refs/heads/develop' &&
         !contains(github.event.head_commit.message, '[skip integration tests]') &&
         !contains(github.event.head_commit.message, '[skip ci]')
        )
      )
    env:
      INTEGRATION_TESTS_ENABLED: "false" # This is the key variable read by NucleusConstants
      NUCLEUS_TEST_LOGGING_FORMAT_SIMPLE: "true"
      # GOOGLE_AI_API_KEY_FOR_TESTS: ${{ secrets.GOOGLE_AI_API_KEY_FOR_TESTS }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Run .NET Aspire Integration Tests
        run: >
          dotnet test ${{ env.SOLUTION_FILE_PATH }} 
          --configuration Release 
          --no-build 
          --filter "Category=Integration"
          --logger "trx;LogFileName=integration_test_results.trx"
      
      - name: Upload Integration Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: "**/integration_test_results.trx"

  sast_scan:
    name: Static Analysis Security Testing (CodeQL)
    runs-on: ubuntu-latest
    needs: build_lint_unit_test 
    if: needs.build_lint_unit_test.outputs.build_status == 'success' && github.event_name == 'pull_request' # Typically run on PRs
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          # Optional: specify a CodeQL config file if you have one
          # config-file: ./.github/codeql/codeql-config.yml
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  nuget_vulnerability_scan:
    name: NuGet Package Vulnerability Scan
    runs-on: ubuntu-latest
    needs: build_lint_unit_test
    if: needs.build_lint_unit_test.outputs.build_status == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore solution to ensure all packages are available
        run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}
      - name: Check for vulnerable NuGet packages
        run: dotnet list ${{ env.SOLUTION_FILE_PATH }} package --vulnerable --include-transitive --verbosity normal
